from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import blue, black
from datetime import datetime
import os


class ReportGenerator:

    @staticmethod
    def generate_report(analysis_data: dict, user: str, logo_path: str = None) -> str:
        os.makedirs('reports', exist_ok=True)
        filename = f"reports/report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
        c = canvas.Canvas(filename, pagesize=A4)
        width, height = A4

        c.setFont("Helvetica-Bold", 20)
        c.setFillColor(blue)
        c.drawString(200, height - 60, "SecurePass Analyzer")
        c.setFillColor(black)
        c.setFont("Helvetica", 10)
        c.drawString(450, height - 30, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 100, f"User: {user}")
        c.line(50, height - 115, width - 50, height - 115)

        y = height - 140
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Password Strength Report")
        y -= 30

        c.setFont("Helvetica", 12)
        score = analysis_data.get('strength_score', 0)
        c.drawString(50, y, f"Strength Score: {score}/100")
        y -= 20
        level = analysis_data.get('strength_level', 'Unknown')
        c.drawString(50, y, f"Strength Level: {level}")
        y -= 20
        entropy = analysis_data.get('entropy_bits', 0)
        c.drawString(50, y, f"Entropy: {entropy:.1f} bits")
        y -= 20
        crack_time = analysis_data.get('estimated_crack_time_display', 'Unknown')
        c.drawString(50, y, f"Estimated Crack Time: {crack_time}")
        y -= 20
        random = analysis_data.get('randomness', False)
        c.drawString(50, y, f"Randomness: {'Good' if random else 'Predictable'}")
        y -= 25

        recs = analysis_data.get('recommendations', [])
        if recs:
            c.setFont("Helvetica-Bold", 12)
            c.drawString(50, y, "Recommendations:")
            y -= 20
            c.setFont("Helvetica", 11)
            for rec in recs[:6]:
                c.drawString(60, y, f"• {rec}")
                y -= 16

        c.setFont("Helvetica", 8)
        c.drawString(50, 40, "Generated by SecurePass Analyzer © 2026")
        c.save()
        return filename